### ISSUE TITLE
the pText in a pTextBox is too far to the left

### ISSUE THREAD

**Issue by Beyley** [Eeveelution/PeppyCodeEngine#12]
This causes the pText to sometimes be inside the border for the pTextBox 
[link](https://i.beyleyisnot.moe/dda54dcd02.png)

**Comment by Eeveelution** [comment]
its just fine on windows, why the fuck is everything different on linux

**Comment by Beyley** [comment]
> its just fine on windows, why the fuck is everything different on linux

Im using a different font

**Comment by Eeveelution** [comment]
closing due to new text renderer being almost ready
